"""change title project

Revision ID: 2c87ad2f11a0
Revises: 58cbe5d08982
Create Date: 2025-12-16 09:45:41.855934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c87ad2f11a0"
down_revision: Union[str, Sequence[str], None] = "58cbe5d08982"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("projects_title_key"), "projects", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("projects_title_key"),
        "projects",
        ["title"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
