"""add session

Revision ID: 370cef84b5f0
Revises: c6a24dbf116f
Create Date: 2025-12-01 14:24:44.856587

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "370cef84b5f0"
down_revision: Union[str, Sequence[str], None] = "c6a24dbf116f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("interview_id", sa.Integer(), nullable=False),
        sa.Column("external_session_id", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PROCESSING",
                "WAITING_FOR_ANSWERS",
                "DONE",
                "ERROR",
                "CANCELLED",
                name="sessionstatusenum",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_session_id"),
    )
    op.create_index(
        op.f("ix_agent_sessions_id"), "agent_sessions", ["id"], unique=False
    )
    op.create_table(
        "agent_session_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("AGENT", "USER", name="sessionmessageroleenum"),
            nullable=False,
        ),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "message_type",
            sa.Enum("QUESTION", "ANSWER", "RESULT", name="sessionmessagetypeenum"),
            nullable=False,
        ),
        sa.Column("iteration_number", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_session_messages_id"),
        "agent_session_messages",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_agent_session_messages_id"), table_name="agent_session_messages"
    )
    op.drop_table("agent_session_messages")
    op.drop_index(op.f("ix_agent_sessions_id"), table_name="agent_sessions")
    op.drop_table("agent_sessions")

    sa.Enum(name="sessionstatusenum").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="sessionmessageroleenum").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="sessionmessagetypeenum").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
