"""rename fields

Revision ID: 58cbe5d08982
Revises: 8ca53889808e
Create Date: 2025-12-16 09:36:43.188737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58cbe5d08982"
down_revision: Union[str, Sequence[str], None] = "8ca53889808e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_session_messages",
        sa.Column("question_external_id", sa.String(), nullable=True),
    )
    op.drop_column("agent_session_messages", "question_id")
    op.alter_column(
        "agent_sessions", "project_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agent_sessions", "project_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column(
        "agent_session_messages",
        sa.Column("question_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("agent_session_messages", "question_external_id")
    # ### end Alembic commands ###
