"""add iteration number into session

Revision ID: 6762b805326a
Revises: 370cef84b5f0
Create Date: 2025-12-01 16:12:00.565319

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6762b805326a"
down_revision: Union[str, Sequence[str], None] = "370cef84b5f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_sessions",
        sa.Column("current_iteration", sa.Integer(), nullable=False, default=1),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_sessions", "current_iteration")
    # ### end Alembic commands ###
