"""add all models

Revision ID: 6845c679cc2a
Revises:
Create Date: 2025-12-15 19:57:55.706700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6845c679cc2a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "FINISHED", name="projectstatusenum"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "agent_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("external_session_id", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PROCESSING",
                "WAITING_FOR_ANSWERS",
                "DONE",
                "ERROR",
                "CANCELLED",
                name="sessionstatusenum",
            ),
            nullable=False,
        ),
        sa.Column("current_iteration", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_session_id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_index(
        op.f("ix_agent_sessions_id"), "agent_sessions", ["id"], unique=False
    )
    op.create_table(
        "project_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("original_name", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_files_id"), "project_files", ["id"], unique=False)
    op.create_table(
        "agent_session_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("AGENT", "USER", name="sessionmessageroleenum"),
            nullable=False,
        ),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "message_type",
            sa.Enum("QUESTION", "ANSWER", "RESULT", name="sessionmessagetypeenum"),
            nullable=False,
        ),
        sa.Column("question_id", sa.String(), nullable=True),
        sa.Column("question_number", sa.Integer(), nullable=True),
        sa.Column(
            "question_status",
            sa.Enum("unanswered", "answered", "skipped", name="questionstatusenum"),
            nullable=True,
        ),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_session_messages_id"),
        "agent_session_messages",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_agent_session_messages_id"), table_name="agent_session_messages"
    )
    op.drop_table("agent_session_messages")
    op.drop_index(op.f("ix_project_files_id"), table_name="project_files")
    op.drop_table("project_files")
    op.drop_index(op.f("ix_agent_sessions_id"), table_name="agent_sessions")
    op.drop_table("agent_sessions")
    op.drop_table("refresh_token")
    op.drop_table("projects")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")

    sa.Enum(name="projectstatusenum").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="sessionstatusenum").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="sessionmessageroleenum").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="sessionmessagetypeenum").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="questionstatusenum").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
