"""update agent sessions for new contract

Revision ID: 726a88ebb731
Revises: ddf6a61ab097
Create Date: 2025-12-13 11:00:41.934469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726a88ebb731'
down_revision: Union[str, Sequence[str], None] = 'ddf6a61ab097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    questionstatusenum = sa.Enum('unanswered', 'answered', 'skipped', 
                                 name='questionstatusenum')
    questionstatusenum.create(op.get_bind(), checkfirst=True)
    
    agentsessionstatusenum = sa.Enum('ASK_USER_GOAL', 'SELECT_OR_CREATE_PROJECT', 
                                     'ASK_USER_CONTEXT', 'CHOOSE_MODE', 
                                     'WAITING_FOR_ANSWERS', 'DRAFT_COLLECTING', 
                                     'VALIDATING', 'GENERATING_REQUIREMENTS', 
                                     'DONE', 'CANCELLED', 'ERROR', 
                                     name='agentsessionstatusenum')
    agentsessionstatusenum.create(op.get_bind(), checkfirst=True)

    op.add_column('agent_session_messages', sa.Column('question_id', sa.String(), nullable=True))
    op.add_column('agent_session_messages', sa.Column('question_number', sa.Integer(), nullable=True))
    op.add_column('agent_session_messages', sa.Column('question_status', questionstatusenum, nullable=True))
    op.add_column('agent_session_messages', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('agent_sessions', sa.Column('agent_session_status', agentsessionstatusenum, nullable=True))
    op.add_column('agent_sessions', sa.Column('callback_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_sessions', 'callback_url')
    op.drop_column('agent_sessions', 'agent_session_status')
    op.drop_column('agent_session_messages', 'explanation')
    op.drop_column('agent_session_messages', 'question_status')
    op.drop_column('agent_session_messages', 'question_number')
    op.drop_column('agent_session_messages', 'question_id')

    agentsessionstatusenum = sa.Enum(name='agentsessionstatusenum')
    agentsessionstatusenum.drop(op.get_bind(), checkfirst=True)

    questionstatusenum = sa.Enum(name='questionstatusenum')
    questionstatusenum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
