"""fix agent session one-to-one to interview

Revision ID: 79cc2da5ab3d
Revises: 7a8b9c0d1e2f
Create Date: 2025-12-03 22:37:11.184011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79cc2da5ab3d"
down_revision: Union[str, Sequence[str], None] = "7a8b9c0d1e2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "agent_sessions_interview_id_key", "agent_sessions", ["interview_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "agent_sessions_interview_id_key", "agent_sessions", type_="unique"
    )
    # ### end Alembic commands ###
