"""add parent_message_id

Revision ID: 8ca53889808e
Revises: 6845c679cc2a
Create Date: 2025-12-15 23:08:07.495829

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ca53889808e"
down_revision: Union[str, Sequence[str], None] = "6845c679cc2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_session_messages",
        sa.Column("parent_message_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "agent_session_messages",
        "agent_session_messages",
        ["parent_message_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "agent_session_messages", type_="foreignkey")
    op.drop_column("agent_session_messages", "parent_message_id")
    # ### end Alembic commands ###
