"""add user goal field

Revision ID: 904a00d569a7
Revises: 2c87ad2f11a0
Create Date: 2025-12-16 09:52:22.810045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "904a00d569a7"
down_revision: Union[str, Sequence[str], None] = "2c87ad2f11a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_sessions", sa.Column("user_goal", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_sessions", "user_goal")
    # ### end Alembic commands ###
