"""add interview files and external id

Revision ID: c6a24dbf116f
Revises: ab38a3730f08
Create Date: 2025-11-30 14:32:08.069778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6a24dbf116f"
down_revision: Union[str, Sequence[str], None] = "ab38a3730f08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interview_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("interview_id", sa.Integer(), nullable=False),
        sa.Column("original_name", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_files_id"), "interview_files", ["id"], unique=False
    )
    op.add_column("interviews", sa.Column("external_id", sa.String(), nullable=True))
    op.drop_column("interviews", "file_path")
    op.drop_column("interviews", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interviews",
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "interviews",
        sa.Column("file_path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("interviews", "external_id")
    op.drop_index(op.f("ix_interview_files_id"), table_name="interview_files")
    op.drop_table("interview_files")
    # ### end Alembic commands ###
