"""del field iteration_number in agent_messages

Revision ID: ddf6a61ab097
Revises: 79cc2da5ab3d
Create Date: 2025-12-03 23:48:24.350962

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ddf6a61ab097"
down_revision: Union[str, Sequence[str], None] = "79cc2da5ab3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_session_messages", "iteration_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_session_messages",
        sa.Column("iteration_number", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
