"""add is_skipped

Revision ID: eae3d1ed4701
Revises: 904a00d569a7
Create Date: 2025-12-16 18:54:00.875473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eae3d1ed4701"
down_revision: Union[str, Sequence[str], None] = "904a00d569a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_session_messages", sa.Column("is_skipped", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_session_messages", "is_skipped")
    # ### end Alembic commands ###
